import fs from 'node:fs';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
const root=new URL('../',import.meta.url);
const app=fs.readFileSync(new URL('app.js',root),'utf8');
const m=app.match(/const EMBEDDED_SEED=(\{.*?\})\nfunction openDB/);
assert.ok(m,'EMBEDDED_SEED não encontrado');
const seed=JSON.parse(m[1]);
const purchase=seed.purchases[0], items=seed.purchaseItems;
assert.equal(seed.schemaVersion,5);
assert.equal(seed.appVersion,'2.8.13');
assert.equal(purchase.date,'2026-09-10');
assert.equal(purchase.marketName,'Supermercados Alvorada');
assert.equal(purchase.cnpj,'17.833.301/0022-23');
assert.equal(purchase.total,350.01);
assert.equal(purchase.itemCount,23);
assert.equal(items.length,23);
assert.equal(Number(items.reduce((s,i)=>s+i.totalAfterDiscount,0).toFixed(2)),350.01);
assert.ok(items.every(i=>Number.isFinite(i.quantity)&&Number.isFinite(i.unitPrice)&&Number.isFinite(i.lineTotal)));
assert.ok(items.every(i=>i.purchaseDate===purchase.date));
const ids=new Set(seed.products.map(p=>p.id)); assert.equal(ids.size,seed.products.length);
const html=fs.readFileSync(new URL('index.html',root),'utf8');
assert.ok(html.includes('id="importStatus"'));
assert.ok(html.includes('geminiModel')&&html.includes('manualContent')&&html.includes('backupBtn'));
assert.ok(!html.includes('id="geminiKey"'));
assert.ok(!html.includes('Chave API Gemini'));
assert.ok(html.includes('motor anti-falhas'));
assert.ok(!fs.existsSync(new URL('data/seed.json',root)),'seed duplicado deve ser removido');
assert.ok(app.includes('validateReceiptData')&&app.includes('Nenhum dado confiável foi produzido.'));
assert.ok(app.includes('DB_VERSION=9'));
assert.ok(app.includes('importListXlsx')&&app.includes('downloadListTemplateXlsx'));
assert.ok(html.includes('id="listXlsxFile"')&&html.includes('id="listTemplateBtn"'));
assert.ok(html.includes('id="newProductBtn"'));
assert.ok(html.includes('id="productSectorFilter"')&&html.includes('id="healthFilter"'));
assert.ok(app.includes('Saudável')&&app.includes('Não saudável')&&app.includes('SECTORS'));

assert.ok(app.includes('computePurchaseFingerprint'));
assert.ok(app.includes('putPurchase'));
assert.ok(app.includes('reconcileVisionWithLocal'));
assert.ok(app.includes('/api/vision'));
assert.ok(app.includes('/api/ocr-space'));
assert.ok(!app.includes('allowDirectGeminiKey===true'));
assert.ok(!app.includes('generateContent?key=${encodeURIComponent(s.geminiApiKey)}'));
assert.ok(!app.includes('geminiApiKey:""'));
assert.ok(app.includes('replace(/R\\$\\s*/ig'));
const server=fs.readFileSync(new URL('server.mjs',root),'utf8');
assert.ok(server.includes('/api/status')&&server.includes('/api/vision')&&server.includes('/api/chat')&&server.includes('/api/ocr-space')&&server.includes('/api/fiscal/consult')&&server.includes('/api/fiscal/danfe'));
assert.ok(server.includes('CONSULTADANFE_API_URL')&&server.includes('CONSULTADANFE_API_KEY')&&server.includes('pdf_base64')&&server.includes('xml_base64'));
assert.ok(html.includes('id="fiscalKey"')&&html.includes('id="consultFiscalBtn"')&&html.includes('id="openDanfeBtn"')&&html.includes('id="fiscalXmlFile"')&&html.includes('id="sendFiscalXmlBtn"')&&html.includes('id="downloadFiscalJsonBtn"'));
assert.ok(server.includes('process.env.GEMINI_API_KEY'));
assert.ok(server.includes('process.env.OCR_SPACE_API_KEY'));
assert.ok(!server.includes('Access-Control-Allow-Origin'));
const sw=fs.readFileSync(new URL('sw.js',root),'utf8');assert.ok(sw.includes('Service worker intentionally disabled'));assert.ok(!sw.includes('data/seed.json'));
const env=fs.readFileSync(new URL('.env.example',root),'utf8');assert.ok(env.includes('GEMINI_API_KEY=')&&env.includes('OCR_SPACE_API_KEY='));
// Browser numeric parser regression: evaluate only its source expression.
const nm=app.match(/const num=\(v\)=>\{[\s\S]*?\n\};/);assert.ok(nm,'num() não encontrado');const browserNum=eval(`(${nm[0].replace(/^const num=/,'').replace(/;$/,'')})`);
assert.equal(browserNum('350,01'),350.01);assert.equal(browserNum('350.01'),350.01);assert.equal(browserNum('1.234,56'),1234.56);assert.equal(browserNum('1.234'),1.234);assert.equal(browserNum(350.01),350.01);
console.log('Compras da JuRe v2.8.13 static/security checks: PASS');
